import os
from datetime import date

WA = "5545991185798"
SITE = "iguacuexecutivetransfer.com.br"
BASE = os.path.expanduser("~/Documents/iguacu-site/cms")
os.makedirs(BASE, exist_ok=True)

def pagina(slug, titulo, keyword, desc, secoes):
    secs = ""
    for i,(h2,txt) in enumerate(secoes):
        bg = "var(--dark)" if i%2==0 else "var(--black)"
        brd = "border-top:1px solid rgba(201,168,76,0.07);" if i>0 else ""
        secs += f'<section style="padding:80px 0;background:{bg};{brd}"><div class="container" style="max-width:860px"><h2 style="font-family:var(--serif);font-size:clamp(1.6rem,3vw,2.2rem);font-weight:300;line-height:1.2;margin-bottom:20px;color:var(--white)">{h2}</h2><p style="font-size:0.88rem;color:var(--gray-l);line-height:1.95">{txt}</p></div></section>'
    nav = f"""<nav class="nav" id="nav"><div class="nav-inner"><a href="../index.html" class="logo"><span class="logo-m">IGUAÇU</span><span class="logo-s">Executive Transfer</span></a><div class="nav-links"><a href="../index.html">Início</a><a href="../pages/transfer-aeroporto.html">Aeroporto</a><a href="../pages/passeios.html">Passeios</a><a href="../pages/transfer-internacional.html">Internacional</a><a href="../pages/sobre.html">Sobre</a><a href="https://wa.me/{WA}" class="nav-cta" target="_blank">Reservar</a></div><button class="hamburger" id="hamburger"><span></span><span></span><span></span></button></div><div class="mobile-menu" id="mobileMenu"><a href="../index.html">Início</a><a href="../pages/transfer-aeroporto.html">Transfer Aeroporto</a><a href="../pages/passeios.html">Passeios</a><a href="../pages/transfer-internacional.html">Transfer Internacional</a><a href="../pages/sobre.html">Sobre Nós</a><a href="https://wa.me/{WA}" target="_blank">Reservar Agora</a></div></nav>"""
    cta = f"""<section class="cta-final"><div class="container"><div class="cta-inner"><p class="eye">Reserve agora</p><h2 class="cta-h2">Fale Agora com um<br><em>Especialista em Foz.</em></h2><p class="cta-sub">Resposta em até 5 minutos pelo WhatsApp. Atendimento 24h em PT · EN · ES.</p><a href="https://wa.me/{WA}" class="btn-gold" target="_blank">Reservar via WhatsApp</a><div class="cta-details"><span>📍 Foz do Iguaçu, PR</span><span>✈️ Aeroporto IGU</span><span>🌍 Tríplice Fronteira</span><span>⏰ 24h · 7 dias</span></div></div></div></section>"""
    footer = f"""<footer class="footer"><div class="container"><div class="footer-bottom" style="border-top:none;padding-top:0"><p>© 2025 Iguaçu Executive Transfer · Foz do Iguaçu · (45) 9 9118-5798</p><a href="../index.html" style="color:var(--gold);font-size:0.68rem">← Voltar ao início</a></div></div></footer><a href="https://wa.me/{WA}" class="wa-float" target="_blank"><svg width="26" height="26" viewBox="0 0 24 24" fill="white"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/></svg></a><script src="../js/main.js"></script>"""
    return f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{titulo} | Iguaçu Executive Transfer</title>
<meta name="description" content="{desc}">
<meta name="keywords" content="{keyword}, transfer executivo foz do iguacu">
<link rel="canonical" href="https://{SITE}/cms/{slug}.html">
<link rel="stylesheet" href="../css/style.css">
</head>
<body>
{nav}
<section class="page-hero"><div class="page-hero-bg"></div><div class="page-hero-grid"></div><div class="page-hero-vline"></div>
<div class="page-hero-content">
<p class="eye-line">Foz do Iguaçu · Tríplice Fronteira</p>
<h1 style="font-family:var(--serif);font-size:clamp(2.4rem,5vw,4rem);font-weight:300;line-height:1.05;margin:18px 0 20px">{titulo}</h1>
<p style="font-size:0.88rem;color:var(--gray-l);line-height:1.8;max-width:540px">{desc}</p>
</div></section>
<div class="divider-gold"></div>
{secs}
{cta}
<section style="padding:60px 0;background:var(--dark);border-top:1px solid rgba(201,168,76,0.07)"><div class="container" style="max-width:860px"><h2 style="font-family:var(--serif);font-size:1.6rem;font-weight:300;margin-bottom:24px">Contato</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px"><div style="background:var(--dark2);padding:20px 24px;border-left:2px solid var(--gold)"><p style="font-size:0.7rem;letter-spacing:0.15em;text-transform:uppercase;color:var(--gold);margin-bottom:8px">WhatsApp</p><a href="https://wa.me/{WA}" style="font-size:0.88rem;color:var(--white)" target="_blank">(45) 9 9118-5798</a></div><div style="background:var(--dark2);padding:20px 24px;border-left:2px solid var(--gold)"><p style="font-size:0.7rem;letter-spacing:0.15em;text-transform:uppercase;color:var(--gold);margin-bottom:8px">Localização</p><p style="font-size:0.88rem;color:var(--white)">Foz do Iguaçu, PR — Brasil</p></div><div style="background:var(--dark2);padding:20px 24px;border-left:2px solid var(--gold)"><p style="font-size:0.7rem;letter-spacing:0.15em;text-transform:uppercase;color:var(--gold);margin-bottom:8px">Disponibilidade</p><p style="font-size:0.88rem;color:var(--white)">24h · 7 dias · PT · EN · ES</p></div><div style="background:var(--dark2);padding:20px 24px;border-left:2px solid var(--gold)"><p style="font-size:0.7rem;letter-spacing:0.15em;text-transform:uppercase;color:var(--gold);margin-bottom:8px">Pagamento</p><p style="font-size:0.88rem;color:var(--white)">Real (BRL) · Dólar (USD)</p></div></div></div></section>
{footer}
</body></html>""" 
paginas = [
  ("taxi-executivo-foz-do-iguacu","Táxi Executivo em Foz do Iguaçu","taxi executivo foz do iguacu","Serviço de táxi executivo premium em Foz do Iguaçu com motorista bilíngue e veículo de alto padrão.",[("O Melhor Táxi Executivo de Foz do Iguaçu","Quando você precisa de mais do que um simples táxi em Foz do Iguaçu, a Iguaçu Executive Transfer oferece serviço completo com veículo premium, motorista profissional bilíngue e pontualidade garantida. Atendemos executivos, turistas e viajantes que valorizam conforto e discrição em cada trajeto."),("Por Que Escolher Táxi Executivo","O táxi executivo em Foz do Iguaçu vai muito além do transporte convencional. Nosso serviço inclui veículo higienizado e premium, motorista trilíngue PT/EN/ES, água mineral a bordo, monitoramento de rota e atendimento personalizado do início ao fim."),("Táxi Executivo para Todos os Destinos em Foz","Atendemos todos os principais destinos de Foz do Iguaçu: Aeroporto IGU, Cataratas, Itaipu, Parque das Aves, hotéis, eventos corporativos e muito mais. Realizamos traslados para Argentina e Paraguai com suporte completo na fronteira."),("Reserva Rápida e Confirmação Imediata","Reservar táxi executivo em Foz com a Iguaçu Executive Transfer é simples. Entre em contato pelo WhatsApp, informe data, horário e destino — confirmação em até 5 minutos com todos os detalhes."),("Táxi Executivo 24 Horas em Foz do Iguaçu","Nosso serviço funciona 24 horas por dia, 7 dias por semana, incluindo feriados. Chegadas na madrugada, embarques cedo pela manhã — estamos disponíveis sem custo adicional de horário.")]),
  ("transporte-executivo-foz-do-iguacu","Transporte Executivo em Foz do Iguaçu","transporte executivo foz do iguacu","Transporte executivo em Foz do Iguaçu com veículos premium e motorista bilíngue. Reserve pelo WhatsApp.",[("Transporte Executivo de Alto Padrão em Foz","A Iguaçu Executive Transfer é referência em transporte executivo em Foz do Iguaçu. Oferecemos experiência completa de mobilidade premium para executivos, empresários e turistas internacionais que exigem pontualidade e discrição."),("Serviços de Transporte Executivo Disponíveis","Nossa frota atende transfers de aeroporto, passeios às Cataratas, traslados para eventos corporativos, viagens intermunicipais e cruzamento de fronteiras para Argentina e Paraguai. Cada serviço é personalizado conforme sua necessidade."),("Motorista Executivo Profissional e Bilíngue","Todos os nossos motoristas são treinados para o mais alto nível de profissionalismo. Fluentes em português, inglês e espanhol, prontos para receber clientes de qualquer país com total conforto de comunicação."),("Transporte Executivo para Empresas em Foz","Atendemos empresas que precisam de transporte executivo regular em Foz do Iguaçu. Condições especiais para contratos corporativos, garantindo pontualidade, discrição e qualidade em todos os deslocamentos."),("Como Contratar Transporte Executivo em Foz","Entre em contato pelo WhatsApp com data, horário e destino. Respondemos em até 5 minutos com confirmação e orçamento transparente, sem taxas ocultas.")]),
  ("transfer-executivo-foz-do-iguacu","Transfer Executivo Foz do Iguaçu","transfer executivo foz do iguacu","Transfer executivo em Foz do Iguaçu com motorista bilíngue, veículo premium e pontualidade garantida 24h.",[("Transfer Executivo Premium em Foz do Iguaçu","O serviço de transfer executivo da Iguaçu Executive Transfer foi desenvolvido para quem não abre mão de qualidade. Com veículos de alto padrão, motorista bilíngue e atendimento personalizado, cada transfer é uma experiência única de conforto."),("Transfer do Aeroporto de Foz do Iguaçu","Realizamos transfer executivo de e para o Aeroporto IGU com monitoramento de voo em tempo real, recepção com plaquinha de identificação e auxílio com bagagens. Chegue ao destino sem estresse."),("Transfer para Hotéis em Foz do Iguaçu","Atendemos todos os hotéis de Foz do Iguaçu com transfer executivo particular. Centro da cidade, região das Cataratas ou qualquer bairro — pontualidade e conforto garantidos."),("Transfer Internacional Argentina e Paraguai","Oferecemos transfer executivo internacional para Puerto Iguazú e Ciudad del Este. Motorista experiente em trâmites aduaneiros e as melhores rotas da Tríplice Fronteira."),("O Diferencial do Transfer Executivo em Foz","Veículo higienizado antes de cada corrida, água mineral gelada, carregador de celular e motorista que antecipa cada necessidade do passageiro. Isso é o que nos diferencia.")]),
  ("motorista-particular-foz-do-iguacu","Motorista Particular em Foz do Iguaçu","motorista particular foz do iguacu","Motorista particular em Foz do Iguaçu com veículo premium e atendimento bilíngue. Reserve 24h pelo WhatsApp.",[("Motorista Particular de Confiança em Foz","Ter um motorista particular em Foz do Iguaçu significa viajar com total tranquilidade. A Iguaçu Executive Transfer oferece motoristas profissionais, treinados e bilíngues para atender suas necessidades com discrição e eficiência."),("Motorista Particular para Passeios Turísticos","Explore Foz do Iguaçu sem depender de tours coletivos. Visite as Cataratas, Itaipu, Parque das Aves e outros atrativos no seu ritmo, com total flexibilidade de horário."),("Motorista Particular para Executivos","Executivos em viagem a negócios em Foz podem contar com motorista particular exclusivo durante toda a estadia. Ideal para reuniões, visitas a parceiros e eventos corporativos."),("Motorista Particular Bilíngue PT EN ES","Nossos motoristas são fluentes em português, inglês e espanhol. Comunicação clara e eficiente durante todos os deslocamentos em Foz do Iguaçu e região."),("Reserve Motorista Particular em Foz","Reserve pelo WhatsApp com data, horário e roteiro. Em até 5 minutos você recebe confirmação, dados do motorista e todas as informações necessárias.")]),
  ("transfer-aeroporto-foz-do-iguacu","Transfer Aeroporto Foz do Iguaçu","transfer aeroporto foz do iguacu","Transfer executivo Aeroporto IGU Foz do Iguaçu. Recepção personalizada e monitoramento de voo 24 horas.",[("Transfer no Aeroporto Internacional de Foz","O Aeroporto Internacional de Foz do Iguaçu IGU é a porta de entrada para as Cataratas. A Iguaçu Executive Transfer oferece transfer executivo com recepção personalizada e veículo premium aguardando na chegada."),("Recepção VIP no Aeroporto IGU","Seu motorista estará na área de desembarque com plaquinha personalizada. Auxiliamos com bagagens e conduzimos diretamente ao veículo premium, sem filas ou espera desnecessária."),("Monitoramento de Voo em Tempo Real","Monitoramos o status do seu voo em tempo real. Atrasos são ajustados automaticamente sem custo adicional — você não precisa avisar nada."),("Transfer para Todos os Destinos de Foz","Do Aeroporto IGU, realizamos transfer para hotéis, Cataratas, Itaipu, eventos corporativos e travessias para Argentina e Paraguai. Um serviço completo para sua chegada em Foz."),("Reserve Transfer no Aeroporto de Foz","Reserve pelo WhatsApp com número do voo, data e destino final. Confirmamos em até 5 minutos com todos os detalhes da sua recepção.")]),
  ("transfer-foz-puerto-iguazu-argentina","Transfer Foz para Puerto Iguazú Argentina","transfer foz do iguacu puerto iguazu argentina","Transfer executivo de Foz do Iguaçu para Puerto Iguazú Argentina. Motorista bilíngue e suporte na fronteira.",[("Transfer Foz do Iguaçu para Puerto Iguazú","A travessia entre Foz e Puerto Iguazú é uma das mais realizadas na Tríplice Fronteira. A Iguaçu Executive Transfer oferece o transfer mais confortável e seguro com motorista bilíngue especializado em cruzamento de fronteira."),("Ponte Internacional Tancredo Neves","A travessia é feita pela Ponte Internacional Tancredo Neves. Nosso motorista conhece os melhores horários para evitar filas, garantindo travessia eficiente e sem stress para a Argentina."),("Aceitamos Real e Dólar para Argentina","Aceitamos pagamento em Real BRL e Dólar USD nos transfers para a Argentina. Taxas transparentes e sem surpresas na hora do pagamento."),("Transfer com Suporte Bilíngue na Fronteira","Nosso motorista bilíngue PT/EN/ES auxilia em toda a comunicação durante a travessia, desde a imigração até a chegada em Puerto Iguazú. Serviço completo para nacionais e internacionais."),("Reserve Transfer Foz para Argentina","Entre em contato pelo WhatsApp com data, horário e número de passageiros. Confirmamos em até 5 minutos com valor e todos os detalhes.")]),
  ("transfer-foz-ciudad-del-este","Transfer Foz para Ciudad del Este Paraguai","transfer foz do iguacu ciudad del este paraguai","Transfer executivo de Foz do Iguaçu para Ciudad del Este no Paraguai. Seguro, confortável e com suporte.",[("Transfer Foz do Iguaçu para Ciudad del Este","Ciudad del Este é conhecida como a capital mundial das compras. A Iguaçu Executive Transfer oferece transfer seguro e confortável de Foz para Ciudad del Este com suporte completo na travessia Brasil-Paraguai."),("Ponte da Amizade Brasil Paraguai","A travessia é feita pela Ponte da Amizade. Nosso motorista conhece os melhores horários para evitar filas e garantir travessia eficiente até o Paraguai."),("O Que Comprar em Ciudad del Este","Ciudad del Este oferece eletrônicos, perfumes, cosméticos e muito mais abaixo do preço do Brasil. Nosso motorista pode orientar sobre os melhores locais e as cotas da Receita Federal."),("Transfer Seguro para Compras no Paraguai","Com nosso transfer, o motorista aguarda enquanto você faz compras. Você tem transporte seguro garantido para o retorno a Foz do Iguaçu."),("Reserve Transfer Foz para Paraguai","Entre em contato pelo WhatsApp. Informamos sobre documentação e confirmamos em até 5 minutos.")]),
  ("transfer-cataratas-brasil","Transfer Cataratas do Iguaçu Brasil","transfer cataratas iguacu brasil particular","Transfer particular para as Cataratas do Iguaçu lado brasileiro. Sem van compartilhada e com flexibilidade.",[("Transfer Exclusivo para as Cataratas do Iguaçu","As Cataratas do Iguaçu são uma das Sete Maravilhas Naturais do Mundo. A Iguaçu Executive Transfer oferece transfer particular para o Parque Nacional com horário flexível e total liberdade para aproveitar cada trilha."),("Parque Nacional do Iguaçu Lado Brasileiro","O lado brasileiro oferece trilhas deslumbrantes e mirantes únicos. Com nosso transfer executivo, você aproveita cada momento sem preocupação com transporte ou horários fixos de van."),("Motorista Aguarda nas Cataratas","Nosso motorista leva você até a entrada e aguarda o retorno pelo tempo que precisar. Você tem total liberdade para explorar as Cataratas no seu próprio ritmo."),("Cataratas mais Parque das Aves no Mesmo Dia","Combine Cataratas e Parque das Aves em um único dia com nosso transfer. Os dois ficam próximos e organizamos o roteiro perfeito para maximizar seu tempo em Foz."),("Reserve Transfer para as Cataratas","Reserve pelo WhatsApp com data, horário e número de passageiros. Confirmamos em até 5 minutos com valor e detalhes.")]),
  ("transfer-cataratas-argentina","Transfer Cataratas del Iguazú Argentina de Foz","transfer cataratas argentina foz","Transfer de Foz para as Cataratas del Iguazú na Argentina. Particular com suporte completo na fronteira.",[("Transfer para as Cataratas Argentinas","As Cataratas del Iguazú no lado argentino são as mais impressionantes desta maravilha natural. A Iguaçu Executive Transfer realiza transfer particular de Foz para as Cataratas argentinas com suporte completo e motorista bilíngue."),("Garganta do Diabo a Experiência Mais Emocionante","A Garganta do Diabo é o ponto mais emocionante das Cataratas del Iguazú. Com nosso transfer você chega lá com total conforto, sem preocupações com fronteira ou transporte."),("Travessia Foz para Argentina nas Cataratas","A travessia leva aproximadamente 1 hora incluindo a fronteira. Nosso motorista conhece todos os trâmites e os melhores horários para uma passagem ágil e sem estresse."),("Passeio de 6 a 8 Horas nas Cataratas Argentinas","O passeio completo nas Cataratas del Iguazú dura em média 6 a 8 horas. Nosso motorista aguarda no local e você retorna a Foz no horário que preferir."),("Reserve Transfer para Cataratas Argentinas","Entre em contato pelo WhatsApp com data, horário e passageiros. Confirmamos em até 5 minutos com valor e detalhes da travessia.")]),
  ("transfer-itaipu-foz","Transfer Itaipu Binacional Foz","transfer itaipu binacional foz do iguacu","Transfer executivo para Itaipu Binacional em Foz do Iguaçu. Passeio particular e flexível.",[("Transfer para Itaipu Binacional em Foz","A Itaipu Binacional é uma das maiores usinas do mundo e principal atrativo de Foz. A Iguaçu Executive Transfer oferece transfer executivo particular para conhecer esta maravilha da engenharia com total conforto."),("Tours Disponíveis em Itaipu","Itaipu oferece tour panorâmico, tour especial e Itaipu Illuminada. Nosso transfer atende todos os tipos de visita e nosso motorista orienta sobre cada experiência disponível."),("Melhor Horário para Visitar Itaipu","Nosso motorista conhece os melhores horários para evitar filas em Itaipu. Uma vantagem exclusiva do nosso serviço de transfer executivo em Foz do Iguaçu."),("Itaipu mais Cataratas no Mesmo Dia","Combine Itaipu com as Cataratas do Iguaçu e Parque das Aves em um roteiro completo. Organizamos o dia para aproveitar ao máximo sua estadia em Foz."),("Reserve Transfer para Itaipu","Informe data, horário e tipo de tour desejado pelo WhatsApp. Confirmamos em até 5 minutos com valor e detalhes completos.")]),
]
for slug, titulo, keyword, desc, secoes in paginas:
    html = pagina(slug, titulo, keyword, desc, secoes)
    path = f"{BASE}/{slug}.html"
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)

hoje = date.today().isoformat()
sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
principais = ["","pages/transfer-aeroporto.html","pages/passeios.html","pages/transfer-internacional.html","pages/sobre.html"]
for p in principais:
    sitemap += f'  <url><loc>https://{SITE}/{p}</loc><lastmod>{hoje}</lastmod><changefreq>weekly</changefreq><priority>0.9</priority></url>\n'
for slug,*_ in paginas:
    sitemap += f'  <url><loc>https://{SITE}/cms/{slug}.html</loc><lastmod>{hoje}</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>\n'
sitemap += '</urlset>'

with open(os.path.expanduser("~/Documents/iguacu-site/sitemap.xml"), "w") as f:
    f.write(sitemap)

with open(os.path.expanduser("~/Documents/iguacu-site/robots.txt"), "w") as f:
    f.write(f"User-agent: *\nAllow: /\n\nSitemap: https://{SITE}/sitemap.xml\n")

print(f"✅ {len(paginas)} páginas CMS geradas!")
print(f"✅ sitemap.xml criado!")
print(f"✅ robots.txt criado!")