import os
from datetime import date

WA = "5545991185798"
SITE = "iguacuexecutivetransfer.com.br"
BASE = os.path.expanduser("~/Documents/iguacu-site/cms")
os.makedirs(BASE, exist_ok=True)

def pagina(slug, titulo, keyword, desc, secoes):
    secs = ""
    for i,(h2,txt) in enumerate(secoes):
        bg = "var(--dark)" if i%2==0 else "var(--black)"
        brd = "border-top:1px solid rgba(201,168,76,0.07);" if i>0 else ""
        secs += f'<section style="padding:80px 0;background:{bg};{brd}"><div class="container" style="max-width:860px"><h2 style="font-family:var(--serif);font-size:clamp(1.6rem,3vw,2.2rem);font-weight:300;line-height:1.2;margin-bottom:20px;color:var(--white)">{h2}</h2><p style="font-size:0.88rem;color:var(--gray-l);line-height:1.95">{txt}</p></div></section>'
    nav = f"""<nav class="nav" id="nav"><div class="nav-inner"><a href="../index.html" class="logo"><span class="logo-m">IGUAÇU</span><span class="logo-s">Executive Transfer</span></a><div class="nav-links"><a href="../index.html">Início</a><a href="../pages/transfer-aeroporto.html">Aeroporto</a><a href="../pages/passeios.html">Passeios</a><a href="../pages/transfer-internacional.html">Internacional</a><a href="../pages/sobre.html">Sobre</a><a href="https://wa.me/{WA}" class="nav-cta" target="_blank">Reservar</a></div><button class="hamburger" id="hamburger"><span></span><span></span><span></span></button></div><div class="mobile-menu" id="mobileMenu"><a href="../index.html">Início</a><a href="../pages/transfer-aeroporto.html">Transfer Aeroporto</a><a href="../pages/passeios.html">Passeios</a><a href="../pages/transfer-internacional.html">Transfer Internacional</a><a href="../pages/sobre.html">Sobre Nós</a><a href="https://wa.me/{WA}" target="_blank">Reservar Agora</a></div></nav>"""
    cta = f"""<section class="cta-final"><div class="container"><div class="cta-inner"><p class="eye">Reserve agora</p><h2 class="cta-h2">Fale Agora com um<br><em>Especialista em Foz.</em></h2><p class="cta-sub">Resposta em até 5 minutos pelo WhatsApp. Atendimento 24h em PT · EN · ES.</p><a href="https://wa.me/{WA}" class="btn-gold" target="_blank">Reservar via WhatsApp</a><div class="cta-details"><span>📍 Foz do Iguaçu, PR</span><span>✈️ Aeroporto IGU</span><span>🌍 Tríplice Fronteira</span><span>⏰ 24h · 7 dias</span></div></div></div></section>"""
    footer = f"""<footer class="footer"><div class="container"><div class="footer-bottom" style="border-top:none;padding-top:0"><p>© 2025 Iguaçu Executive Transfer · Foz do Iguaçu · (45) 9 9118-5798</p><a href="../index.html" style="color:var(--gold);font-size:0.68rem">← Voltar ao início</a></div></div></footer><a href="https://wa.me/{WA}" class="wa-float" target="_blank"><svg width="26" height="26" viewBox="0 0 24 24" fill="white"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/></svg></a><script src="../js/main.js"></script>"""
    return f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{titulo} | Iguaçu Executive Transfer</title>
<meta name="description" content="{desc}">
<meta name="keywords" content="{keyword}, transfer executivo foz do iguacu">
<link rel="canonical" href="https://{SITE}/cms/{slug}.html">
<link rel="stylesheet" href="../css/style.css">
</head>
<body>
{nav}
<section class="page-hero"><div class="page-hero-bg"></div><div class="page-hero-grid"></div><div class="page-hero-vline"></div>
<div class="page-hero-content">
<p class="eye-line">Foz do Iguaçu · Tríplice Fronteira</p>
<h1 style="font-family:var(--serif);font-size:clamp(2.4rem,5vw,4rem);font-weight:300;line-height:1.05;margin:18px 0 20px">{titulo}</h1>
<p style="font-size:0.88rem;color:var(--gray-l);line-height:1.8;max-width:540px">{desc}</p>
</div></section>
<div class="divider-gold"></div>
{secs}
{cta}
<section style="padding:60px 0;background:var(--dark);border-top:1px solid rgba(201,168,76,0.07)"><div class="container" style="max-width:860px"><h2 style="font-family:var(--serif);font-size:1.6rem;font-weight:300;margin-bottom:24px">Contato</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px"><div style="background:var(--dark2);padding:20px 24px;border-left:2px solid var(--gold)"><p style="font-size:0.7rem;letter-spacing:0.15em;text-transform:uppercase;color:var(--gold);margin-bottom:8px">WhatsApp</p><a href="https://wa.me/{WA}" style="font-size:0.88rem;color:var(--white)" target="_blank">(45) 9 9118-5798</a></div><div style="background:var(--dark2);padding:20px 24px;border-left:2px solid var(--gold)"><p style="font-size:0.7rem;letter-spacing:0.15em;text-transform:uppercase;color:var(--gold);margin-bottom:8px">Localização</p><p style="font-size:0.88rem;color:var(--white)">Foz do Iguaçu, PR — Brasil</p></div><div style="background:var(--dark2);padding:20px 24px;border-left:2px solid var(--gold)"><p style="font-size:0.7rem;letter-spacing:0.15em;text-transform:uppercase;color:var(--gold);margin-bottom:8px">Disponibilidade</p><p style="font-size:0.88rem;color:var(--white)">24h · 7 dias · PT · EN · ES</p></div><div style="background:var(--dark2);padding:20px 24px;border-left:2px solid var(--gold)"><p style="font-size:0.7rem;letter-spacing:0.15em;text-transform:uppercase;color:var(--gold);margin-bottom:8px">Pagamento</p><p style="font-size:0.88rem;color:var(--white)">Real (BRL) · Dólar (USD)</p></div></div></div></section>
{footer}
</body></html>""" 
paginas = [
  ("taxi-executivo-foz-do-iguacu","Táxi Executivo em Foz do Iguaçu","taxi executivo foz do iguacu","Serviço de táxi executivo premium em Foz do Iguaçu com motorista bilíngue e veículo de alto padrão.",[("O Melhor Táxi Executivo de Foz do Iguaçu","Quando você precisa de mais do que um simples táxi em Foz do Iguaçu, a Iguaçu Executive Transfer oferece serviço completo com veículo premium, motorista profissional bilíngue e pontualidade garantida. Atendemos executivos, turistas e viajantes que valorizam conforto e discrição em cada trajeto."),("Por Que Escolher Táxi Executivo","O táxi executivo em Foz do Iguaçu vai muito além do transporte convencional. Nosso serviço inclui veículo higienizado e premium, motorista trilíngue PT/EN/ES, água mineral a bordo, monitoramento de rota e atendimento personalizado do início ao fim."),("Táxi Executivo para Todos os Destinos em Foz","Atendemos todos os principais destinos de Foz do Iguaçu: Aeroporto IGU, Cataratas, Itaipu, Parque das Aves, hotéis, eventos corporativos e muito mais. Realizamos traslados para Argentina e Paraguai com suporte completo na fronteira."),("Reserva Rápida e Confirmação Imediata","Reservar táxi executivo em Foz com a Iguaçu Executive Transfer é simples. Entre em contato pelo WhatsApp, informe data, horário e destino — confirmação em até 5 minutos com todos os detalhes."),("Táxi Executivo 24 Horas em Foz do Iguaçu","Nosso serviço funciona 24 horas por dia, 7 dias por semana, incluindo feriados. Chegadas na madrugada, embarques cedo pela manhã — estamos disponíveis sem custo adicional de horário.")]),
  ("transporte-executivo-foz-do-iguacu","Transporte Executivo em Foz do Iguaçu","transporte executivo foz do iguacu","Transporte executivo em Foz do Iguaçu com veículos premium e motorista bilíngue. Reserve pelo WhatsApp.",[("Transporte Executivo de Alto Padrão em Foz","A Iguaçu Executive Transfer é referência em transporte executivo em Foz do Iguaçu. Oferecemos experiência completa de mobilidade premium para executivos, empresários e turistas internacionais que exigem pontualidade e discrição."),("Serviços de Transporte Executivo Disponíveis","Nossa frota atende transfers de aeroporto, passeios às Cataratas, traslados para eventos corporativos, viagens intermunicipais e cruzamento de fronteiras para Argentina e Paraguai. Cada serviço é personalizado conforme sua necessidade."),("Motorista Executivo Profissional e Bilíngue","Todos os nossos motoristas são treinados para o mais alto nível de profissionalismo. Fluentes em português, inglês e espanhol, prontos para receber clientes de qualquer país com total conforto de comunicação."),("Transporte Executivo para Empresas em Foz","Atendemos empresas que precisam de transporte executivo regular em Foz do Iguaçu. Condições especiais para contratos corporativos, garantindo pontualidade, discrição e qualidade em todos os deslocamentos."),("Como Contratar Transporte Executivo em Foz","Entre em contato pelo WhatsApp com data, horário e destino. Respondemos em até 5 minutos com confirmação e orçamento transparente, sem taxas ocultas.")]),
  ("transfer-executivo-foz-do-iguacu","Transfer Executivo Foz do Iguaçu","transfer executivo foz do iguacu","Transfer executivo em Foz do Iguaçu com motorista bilíngue, veículo premium e pontualidade garantida 24h.",[("Transfer Executivo Premium em Foz do Iguaçu","O serviço de transfer executivo da Iguaçu Executive Transfer foi desenvolvido para quem não abre mão de qualidade. Com veículos de alto padrão, motorista bilíngue e atendimento personalizado, cada transfer é uma experiência única de conforto."),("Transfer do Aeroporto de Foz do Iguaçu","Realizamos transfer executivo de e para o Aeroporto IGU com monitoramento de voo em tempo real, recepção com plaquinha de identificação e auxílio com bagagens. Chegue ao destino sem estresse."),("Transfer para Hotéis em Foz do Iguaçu","Atendemos todos os hotéis de Foz do Iguaçu com transfer executivo particular. Centro da cidade, região das Cataratas ou qualquer bairro — pontualidade e conforto garantidos."),("Transfer Internacional Argentina e Paraguai","Oferecemos transfer executivo internacional para Puerto Iguazú e Ciudad del Este. Motorista experiente em trâmites aduaneiros e as melhores rotas da Tríplice Fronteira."),("O Diferencial do Transfer Executivo em Foz","Veículo higienizado antes de cada corrida, água mineral gelada, carregador de celular e motorista que antecipa cada necessidade do passageiro. Isso é o que nos diferencia.")]),
  ("motorista-particular-foz-do-iguacu","Motorista Particular em Foz do Iguaçu","motorista particular foz do iguacu","Motorista particular em Foz do Iguaçu com veículo premium e atendimento bilíngue. Reserve 24h pelo WhatsApp.",[("Motorista Particular de Confiança em Foz","Ter um motorista particular em Foz do Iguaçu significa viajar com total tranquilidade. A Iguaçu Executive Transfer oferece motoristas profissionais, treinados e bilíngues para atender suas necessidades com discrição e eficiência."),("Motorista Particular para Passeios Turísticos","Explore Foz do Iguaçu sem depender de tours coletivos. Visite as Cataratas, Itaipu, Parque das Aves e outros atrativos no seu ritmo, com total flexibilidade de horário."),("Motorista Particular para Executivos","Executivos em viagem a negócios em Foz podem contar com motorista particular exclusivo durante toda a estadia. Ideal para reuniões, visitas a parceiros e eventos corporativos."),("Motorista Particular Bilíngue PT EN ES","Nossos motoristas são fluentes em português, inglês e espanhol. Comunicação clara e eficiente durante todos os deslocamentos em Foz do Iguaçu e região."),("Reserve Motorista Particular em Foz","Reserve pelo WhatsApp com data, horário e roteiro. Em até 5 minutos você recebe confirmação, dados do motorista e todas as informações necessárias.")]),
  ("transfer-aeroporto-foz-do-iguacu","Transfer Aeroporto Foz do Iguaçu","transfer aeroporto foz do iguacu","Transfer executivo Aeroporto IGU Foz do Iguaçu. Recepção personalizada e monitoramento de voo 24 horas.",[("Transfer no Aeroporto Internacional de Foz","O Aeroporto Internacional de Foz do Iguaçu IGU é a porta de entrada para as Cataratas. A Iguaçu Executive Transfer oferece transfer executivo com recepção personalizada e veículo premium aguardando na chegada."),("Recepção VIP no Aeroporto IGU","Seu motorista estará na área de desembarque com plaquinha personalizada. Auxiliamos com bagagens e conduzimos diretamente ao veículo premium, sem filas ou espera desnecessária."),("Monitoramento de Voo em Tempo Real","Monitoramos o status do seu voo em tempo real. Atrasos são ajustados automaticamente sem custo adicional — você não precisa avisar nada."),("Transfer para Todos os Destinos de Foz","Do Aeroporto IGU, realizamos transfer para hotéis, Cataratas, Itaipu, eventos corporativos e travessias para Argentina e Paraguai. Um serviço completo para sua chegada em Foz."),("Reserve Transfer no Aeroporto de Foz","Reserve pelo WhatsApp com número do voo, data e destino final. Confirmamos em até 5 minutos com todos os detalhes da sua recepção.")]),
  ("transfer-foz-puerto-iguazu-argentina","Transfer Foz para Puerto Iguazú Argentina","transfer foz do iguacu puerto iguazu argentina","Transfer executivo de Foz do Iguaçu para Puerto Iguazú Argentina. Motorista bilíngue e suporte na fronteira.",[("Transfer Foz do Iguaçu para Puerto Iguazú","A travessia entre Foz e Puerto Iguazú é uma das mais realizadas na Tríplice Fronteira. A Iguaçu Executive Transfer oferece o transfer mais confortável e seguro com motorista bilíngue especializado em cruzamento de fronteira."),("Ponte Internacional Tancredo Neves","A travessia é feita pela Ponte Internacional Tancredo Neves. Nosso motorista conhece os melhores horários para evitar filas, garantindo travessia eficiente e sem stress para a Argentina."),("Aceitamos Real e Dólar para Argentina","Aceitamos pagamento em Real BRL e Dólar USD nos transfers para a Argentina. Taxas transparentes e sem surpresas na hora do pagamento."),("Transfer com Suporte Bilíngue na Fronteira","Nosso motorista bilíngue PT/EN/ES auxilia em toda a comunicação durante a travessia, desde a imigração até a chegada em Puerto Iguazú. Serviço completo para nacionais e internacionais."),("Reserve Transfer Foz para Argentina","Entre em contato pelo WhatsApp com data, horário e número de passageiros. Confirmamos em até 5 minutos com valor e todos os detalhes.")]),
  ("transfer-foz-ciudad-del-este","Transfer Foz para Ciudad del Este Paraguai","transfer foz do iguacu ciudad del este paraguai","Transfer executivo de Foz do Iguaçu para Ciudad del Este no Paraguai. Seguro, confortável e com suporte.",[("Transfer Foz do Iguaçu para Ciudad del Este","Ciudad del Este é conhecida como a capital mundial das compras. A Iguaçu Executive Transfer oferece transfer seguro e confortável de Foz para Ciudad del Este com suporte completo na travessia Brasil-Paraguai."),("Ponte da Amizade Brasil Paraguai","A travessia é feita pela Ponte da Amizade. Nosso motorista conhece os melhores horários para evitar filas e garantir travessia eficiente até o Paraguai."),("O Que Comprar em Ciudad del Este","Ciudad del Este oferece eletrônicos, perfumes, cosméticos e muito mais abaixo do preço do Brasil. Nosso motorista pode orientar sobre os melhores locais e as cotas da Receita Federal."),("Transfer Seguro para Compras no Paraguai","Com nosso transfer, o motorista aguarda enquanto você faz compras. Você tem transporte seguro garantido para o retorno a Foz do Iguaçu."),("Reserve Transfer Foz para Paraguai","Entre em contato pelo WhatsApp. Informamos sobre documentação e confirmamos em até 5 minutos.")]),
  ("transfer-cataratas-brasil","Transfer Cataratas do Iguaçu Brasil","transfer cataratas iguacu brasil particular","Transfer particular para as Cataratas do Iguaçu lado brasileiro. Sem van compartilhada e com flexibilidade.",[("Transfer Exclusivo para as Cataratas do Iguaçu","As Cataratas do Iguaçu são uma das Sete Maravilhas Naturais do Mundo. A Iguaçu Executive Transfer oferece transfer particular para o Parque Nacional com horário flexível e total liberdade para aproveitar cada trilha."),("Parque Nacional do Iguaçu Lado Brasileiro","O lado brasileiro oferece trilhas deslumbrantes e mirantes únicos. Com nosso transfer executivo, você aproveita cada momento sem preocupação com transporte ou horários fixos de van."),("Motorista Aguarda nas Cataratas","Nosso motorista leva você até a entrada e aguarda o retorno pelo tempo que precisar. Você tem total liberdade para explorar as Cataratas no seu próprio ritmo."),("Cataratas mais Parque das Aves no Mesmo Dia","Combine Cataratas e Parque das Aves em um único dia com nosso transfer. Os dois ficam próximos e organizamos o roteiro perfeito para maximizar seu tempo em Foz."),("Reserve Transfer para as Cataratas","Reserve pelo WhatsApp com data, horário e número de passageiros. Confirmamos em até 5 minutos com valor e detalhes.")]),
  ("transfer-cataratas-argentina","Transfer Cataratas del Iguazú Argentina de Foz","transfer cataratas argentina foz","Transfer de Foz para as Cataratas del Iguazú na Argentina. Particular com suporte completo na fronteira.",[("Transfer para as Cataratas Argentinas","As Cataratas del Iguazú no lado argentino são as mais impressionantes desta maravilha natural. A Iguaçu Executive Transfer realiza transfer particular de Foz para as Cataratas argentinas com suporte completo e motorista bilíngue."),("Garganta do Diabo a Experiência Mais Emocionante","A Garganta do Diabo é o ponto mais emocionante das Cataratas del Iguazú. Com nosso transfer você chega lá com total conforto, sem preocupações com fronteira ou transporte."),("Travessia Foz para Argentina nas Cataratas","A travessia leva aproximadamente 1 hora incluindo a fronteira. Nosso motorista conhece todos os trâmites e os melhores horários para uma passagem ágil e sem estresse."),("Passeio de 6 a 8 Horas nas Cataratas Argentinas","O passeio completo nas Cataratas del Iguazú dura em média 6 a 8 horas. Nosso motorista aguarda no local e você retorna a Foz no horário que preferir."),("Reserve Transfer para Cataratas Argentinas","Entre em contato pelo WhatsApp com data, horário e passageiros. Confirmamos em até 5 minutos com valor e detalhes da travessia.")]),
  ("transfer-itaipu-foz","Transfer Itaipu Binacional Foz","transfer itaipu binacional foz do iguacu","Transfer executivo para Itaipu Binacional em Foz do Iguaçu. Passeio particular e flexível.",[("Transfer para Itaipu Binacional em Foz","A Itaipu Binacional é uma das maiores usinas do mundo e principal atrativo de Foz. A Iguaçu Executive Transfer oferece transfer executivo particular para conhecer esta maravilha da engenharia com total conforto."),("Tours Disponíveis em Itaipu","Itaipu oferece tour panorâmico, tour especial e Itaipu Illuminada. Nosso transfer atende todos os tipos de visita e nosso motorista orienta sobre cada experiência disponível."),("Melhor Horário para Visitar Itaipu","Nosso motorista conhece os melhores horários para evitar filas em Itaipu. Uma vantagem exclusiva do nosso serviço de transfer executivo em Foz do Iguaçu."),("Itaipu mais Cataratas no Mesmo Dia","Combine Itaipu com as Cataratas do Iguaçu e Parque das Aves em um roteiro completo. Organizamos o dia para aproveitar ao máximo sua estadia em Foz."),("Reserve Transfer para Itaipu","Informe data, horário e tipo de tour desejado pelo WhatsApp. Confirmamos em até 5 minutos com valor e detalhes completos.")]),
]
for slug, titulo, keyword, desc, secoes in paginas:
    html = pagina(slug, titulo, keyword, desc, secoes)
    path = f"{BASE}/{slug}.html"
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)

hoje = date.today().isoformat()
sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
principais = ["","pages/transfer-aeroporto.html","pages/passeios.html","pages/transfer-internacional.html","pages/sobre.html"]
for p in principais:
    sitemap += f'  <url><loc>https://{SITE}/{p}</loc><lastmod>{hoje}</lastmod><changefreq>weekly</changefreq><priority>0.9</priority></url>\n'
for slug,*_ in paginas:
    sitemap += f'  <url><loc>https://{SITE}/cms/{slug}.html</loc><lastmod>{hoje}</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>\n'
sitemap += '</urlset>'

with open(os.path.expanduser("~/Documents/iguacu-site/sitemap.xml"), "w") as f:
    f.write(sitemap)

with open(os.path.expanduser("~/Documents/iguacu-site/robots.txt"), "w") as f:
    f.write(f"User-agent: *\nAllow: /\n\nSitemap: https://{SITE}/sitemap.xml\n")

print(f"✅ {len(paginas)} páginas CMS geradas!")
print(f"✅ sitemap.xml criado!")
print(f"✅ robots.txt criado!")
paginas2 = [
  ("transfer-foz-cascavel","Transfer Foz do Iguaçu para Cascavel PR","transfer foz cascavel parana","Transfer executivo de Foz do Iguaçu para Cascavel PR. Confortável, pontual e com motorista profissional.",[("Transfer Foz–Cascavel com Conforto","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Cascavel com conforto e segurança. A viagem de aproximadamente 1h30min se torna muito mais agradável em veículo premium com motorista profissional e experiente na rota."),("Transfer Corporativo Foz–Cascavel","Para executivos e empresários que viajam entre Foz do Iguaçu e Cascavel regularmente, oferecemos transfer corporativo com total discrição. Ideal para reuniões de negócios no Oeste do Paraná."),("Foz do Iguaçu para Cascavel — A Melhor Opção","O transfer executivo é a melhor opção para viajar entre Foz e Cascavel com privacidade, pontualidade e sem o desgaste de dirigir em rodovia. Chegue descansado ao seu destino."),("Paradas Personalizadas na Rota Foz–Cascavel","Nosso transfer pode incluir paradas em cidades como Medianeira, Missal ou outras na rota conforme sua necessidade. Personalizamos o roteiro para atender seus compromissos."),("Reserve Transfer Foz–Cascavel pelo WhatsApp","Entre em contato pelo WhatsApp com data, horário e endereços de origem e destino. Orçamento em até 5 minutos.")]),
  ("transfer-foz-umuarama","Transfer Foz do Iguaçu para Umuarama PR","transfer foz do iguacu umuarama parana","Transfer executivo de Foz do Iguaçu para Umuarama PR. Viagem confortável com motorista profissional.",[("Transfer Executivo Foz–Umuarama","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Umuarama no Noroeste do Paraná. Viagem de aproximadamente 3 horas com total conforto em veículo premium."),("Transfer Corporativo Foz para Umuarama","Para empresários e executivos com negócios entre Foz do Iguaçu e Umuarama, oferecemos transfer corporativo com pontualidade e discrição garantidas em toda a viagem."),("Conforto na Viagem Foz–Umuarama","Viaje entre Foz do Iguaçu e Umuarama com ar-condicionado, água mineral, carregador de celular e motorista profissional. Muito mais confortável que ônibus ou dirigir sozinho."),("Umuarama e Região Noroeste do Paraná","Atendemos Umuarama e toda a região Noroeste do Paraná a partir de Foz do Iguaçu. Cidades como Cruzeiro do Oeste, Perobal e Maria Helena também são atendidas na mesma rota."),("Reserve Transfer Foz–Umuarama","Entre em contato pelo WhatsApp com data e horário. Confirmamos orçamento em até 5 minutos.")]),
  ("transfer-foz-maringa","Transfer Foz do Iguaçu para Maringá PR","transfer foz do iguacu maringa parana","Transfer executivo de Foz do Iguaçu para Maringá PR. Viagem premium com motorista profissional.",[("Transfer Executivo Foz–Maringá","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Maringá com conforto e segurança. A viagem de aproximadamente 4 horas se torna muito mais agradável em veículo premium."),("Transfer Corporativo Foz para Maringá","Maringá é um dos principais centros empresariais do Paraná. Para executivos que viajam entre Foz do Iguaçu e Maringá, oferecemos transfer corporativo com total profissionalismo e discrição."),("Maringá e Região Norte do Paraná","Além de Maringá, atendemos toda a região Norte do Paraná a partir de Foz do Iguaçu. Sarandi, Paiçandu, Mandaguari e outras cidades próximas também são atendidas."),("Viagem Foz–Maringá com Paradas Personalizadas","Nosso transfer pode incluir paradas em cidades como Cascavel, Campo Mourão ou outras na rota conforme necessidade. Roteiro personalizado para sua viagem."),("Reserve Transfer Foz–Maringá pelo WhatsApp","Entre em contato com data, horário e endereços. Orçamento em até 5 minutos.")]),
  ("transfer-foz-londrina","Transfer Foz do Iguaçu para Londrina PR","transfer foz do iguacu londrina parana","Transfer executivo de Foz do Iguaçu para Londrina PR. Confortável e direto com motorista profissional.",[("Transfer Executivo Foz–Londrina","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Londrina, segunda maior cidade do Paraná. Viagem de aproximadamente 5 horas com total conforto em veículo premium."),("Transfer Corporativo Foz para Londrina","Londrina é um importante polo empresarial e universitário do Paraná. Para executivos e empresários que viajam entre Foz e Londrina, oferecemos transfer corporativo com pontualidade e profissionalismo."),("Conforto na Longa Viagem Foz–Londrina","A viagem entre Foz do Iguaçu e Londrina dura cerca de 5 horas. Em nosso veículo premium com ar-condicionado, água mineral e Wi-Fi, o tempo passa muito mais rápido e você chega descansado."),("Londrina e Região Norte Pioneiro do Paraná","Além de Londrina, atendemos toda a região Norte Pioneiro do Paraná. Cornélio Procópio, Jacarezinho e outras cidades da região são atendidas a partir de Foz do Iguaçu."),("Reserve Transfer Foz–Londrina pelo WhatsApp","Entre em contato com data, horário e endereços de origem e destino. Orçamento em até 5 minutos.")]),
  ("transfer-foz-sao-paulo","Transfer Foz do Iguaçu para São Paulo SP","transfer foz do iguacu sao paulo","Transfer executivo de Foz do Iguaçu para São Paulo SP. Viagem longa com máximo conforto e segurança.",[("Transfer Executivo Foz–São Paulo","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e São Paulo para clientes que precisam de máximo conforto em uma viagem longa. Motorista experiente e veículo premium para aproximadamente 10 horas de viagem."),("Por Que Escolher Transfer em Vez de Avião","Para quem tem flexibilidade de horário, o transfer executivo Foz–São Paulo oferece porta a porta sem filas de aeroporto, bagagem sem limite e total privacidade. Ideal para executivos com muito material ou que preferem chegar diretamente ao destino."),("Transfer Foz–São Paulo para Grupos","Para grupos que precisam ir de Foz do Iguaçu para São Paulo, o transfer executivo pode ser mais econômico e conveniente que vários passagens aéreas, além de oferecer muito mais conforto e flexibilidade de horário."),("Paradas na Rota Foz–São Paulo","A rota entre Foz do Iguaçu e São Paulo passa por Cascavel, Campo Mourão, Maringá, Londrina e outras cidades. Podemos incluir paradas conforme necessidade, tornando a viagem produtiva."),("Reserve Transfer Foz–São Paulo pelo WhatsApp","Para o transfer de longa distância Foz–São Paulo, entre em contato pelo WhatsApp com antecedência. Orçamento personalizado em até 5 minutos.")]),
  ("transfer-foz-guaira","Transfer Foz do Iguaçu para Guaíra PR","transfer foz do iguacu guaira parana","Transfer executivo de Foz do Iguaçu para Guaíra PR. Confortável e direto com motorista profissional.",[("Transfer Executivo Foz–Guaíra","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Guaíra no Noroeste do Paraná. Viagem de aproximadamente 2 horas com total conforto em veículo premium e motorista profissional."),("Guaíra — Porta de Entrada para o Noroeste","Guaíra é um importante município na divisa com Mato Grosso do Sul e Paraguai. Para executivos e turistas que precisam de transfer entre Foz do Iguaçu e Guaíra, oferecemos o serviço mais confortável da rota."),("Transfer Foz–Guaíra para Turismo","Guaíra possui o Parque Nacional de Ilha Grande, belezas naturais às margens do Rio Paraná e a histórica localização das Sete Quedas. Transfer executivo para turistas que desejam explorar a região."),("Transfer Corporativo Foz–Guaíra","Para empresários com negócios entre Foz do Iguaçu e Guaíra, oferecemos transfer corporativo com pontualidade e discrição. Atendemos também cidades próximas como Terra Roxa e Altônia."),("Reserve Transfer Foz–Guaíra pelo WhatsApp","Entre em contato pelo WhatsApp com data, horário e endereços. Orçamento em até 5 minutos.")]),
  ("transfer-foz-toledo","Transfer Foz do Iguaçu para Toledo PR","transfer foz do iguacu toledo parana","Transfer executivo de Foz do Iguaçu para Toledo PR. Pontual, confortável e com motorista profissional.",[("Transfer Executivo Foz–Toledo","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Toledo, importante município do Oeste do Paraná. Viagem de aproximadamente 1 hora com total conforto em veículo premium."),("Toledo PR — Centro do Oeste Paranaense","Toledo é um dos municípios mais prósperos do Oeste do Paraná e recebe frequentemente executivos de Foz do Iguaçu. Nosso transfer corporativo é a opção mais confortável e profissional para esta rota."),("Transfer Foz–Toledo para Eventos e Reuniões","Para participar de eventos, feiras e reuniões em Toledo vindo de Foz do Iguaçu, nosso transfer executivo garante chegada pontual e descansada. Ideal para fazer boa impressão nos compromissos."),("Toledo e Cidades Vizinhas do Oeste do Paraná","Além de Toledo, atendemos Marechal Cândido Rondon, Palotina, Assis Chateaubriand e outras cidades do Oeste do Paraná a partir de Foz do Iguaçu."),("Reserve Transfer Foz–Toledo pelo WhatsApp","Entre em contato com data, horário e endereços. Confirmamos em até 5 minutos.")]),
  ("transfer-foz-curitiba","Transfer Foz do Iguaçu para Curitiba PR","transfer foz do iguacu curitiba parana","Transfer executivo de Foz do Iguaçu para Curitiba PR. Viagem confortável com motorista profissional.",[("Transfer Executivo Foz–Curitiba","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Curitiba com conforto e segurança. A viagem de aproximadamente 6 horas se torna muito mais agradável em veículo premium com motorista experiente."),("Transfer Corporativo Foz para Curitiba","Curitiba é a capital do Paraná e um dos principais centros de negócios do Sul do Brasil. Para executivos que viajam entre Foz do Iguaçu e Curitiba, oferecemos transfer corporativo com total profissionalismo."),("Conforto na Viagem Foz–Curitiba de 6 Horas","A viagem entre Foz do Iguaçu e Curitiba dura cerca de 6 horas. Em nosso veículo premium com ar-condicionado, água mineral, carregador e Wi-Fi, você chega descansado e pronto para seus compromissos."),("Paradas na Rota Foz–Curitiba","A rota passa por Cascavel, Guarapuava e Ponta Grossa. Podemos incluir paradas conforme necessidade para tornar sua viagem mais produtiva e personalizada."),("Reserve Transfer Foz–Curitiba pelo WhatsApp","Entre em contato com data e horário. Orçamento em até 5 minutos.")]),
  ("transfer-foz-argentina-misiones","Transfer Foz do Iguaçu para Misiones Argentina","transfer foz do iguacu misiones argentina","Transfer executivo de Foz do Iguaçu para a Província de Misiones na Argentina. Motorista bilíngue.",[("Transfer Foz do Iguaçu para Misiones Argentina","A Iguaçu Executive Transfer realiza transfer executivo de Foz do Iguaçu para a Província de Misiones na Argentina. Com motorista bilíngue especializado em travessia de fronteira, garantimos a viagem mais confortável e segura para esta região."),("Misiones — Turismo e Negócios na Argentina","A Província de Misiones na Argentina é famosa pelas Cataratas del Iguazú, pela natureza exuberante e pelo mate. Para turistas e executivos que precisam ir a Misiones a partir de Foz, oferecemos o melhor transfer disponível."),("Transfer para Cidades de Misiones Argentina","Além de Puerto Iguazú, atendemos outras cidades da Província de Misiones como Eldorado, Posadas e San Ignacio. Motorista experiente nas rotas argentinas e nos trâmites de fronteira."),("Aceitamos Real e Dólar para Misiones","Para o transfer para Misiones na Argentina, aceitamos pagamento em Real BRL e Dólar USD. Taxas transparentes e sem surpresas para viajantes nacionais e internacionais."),("Reserve Transfer Foz–Misiones Argentina","Entre em contato pelo WhatsApp com data, destino em Misiones e número de passageiros. Confirmamos em até 5 minutos.")]),
  ("transfer-foz-aeroporto-posadas","Transfer Foz do Iguaçu para Aeroporto de Posadas Argentina","transfer foz aeroporto posadas misiones argentina","Transfer de Foz do Iguaçu para o Aeroporto de Posadas em Misiones Argentina. Motorista bilíngue.",[("Transfer para o Aeroporto de Posadas em Misiones","A Iguaçu Executive Transfer realiza transfer executivo de Foz do Iguaçu para o Aeroporto Internacional Libertador General José de San Martín em Posadas, capital de Misiones na Argentina. Motorista bilíngue e experiente na rota."),("Posadas — Capital de Misiones Argentina","Posadas é a capital da Província de Misiones e possui conexões aéreas para Buenos Aires e outras cidades argentinas. Para quem precisa embarcar em Posadas vindo de Foz do Iguaçu, nosso transfer é a melhor opção."),("Transfer Longa Distância Foz–Posadas","O transfer de Foz do Iguaçu para Posadas percorre aproximadamente 300km pela Argentina. Motorista experiente nas rodovias argentinas e total suporte em todos os trâmites de fronteira e documentação."),("Aceitamos Real Dólar e Peso Argentino","Para o transfer para Posadas, aceitamos pagamento em Real BRL, Dólar USD e Peso Argentino ARS. Facilitamos ao máximo para viajantes de qualquer origem."),("Reserve Transfer Foz–Aeroporto Posadas","Entre em contato pelo WhatsApp com número do voo, data e horário. Confirmamos em até 5 minutos com todos os detalhes.")]),
  ("transfer-foz-pato-branco","Transfer Foz do Iguaçu para Pato Branco PR","transfer foz do iguacu pato branco parana","Transfer executivo de Foz do Iguaçu para Pato Branco PR. Confortável e direto com motorista profissional.",[("Transfer Executivo Foz–Pato Branco","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Pato Branco no Sudoeste do Paraná. Viagem de aproximadamente 2h30min com total conforto em veículo premium."),("Pato Branco — Centro do Sudoeste Paranaense","Pato Branco é um dos municípios mais desenvolvidos do Sudoeste do Paraná, com importante polo tecnológico e empresarial. Transfer executivo entre Foz e Pato Branco para executivos e empresários da região."),("Transfer Foz–Pato Branco para Toda a Região","Além de Pato Branco, atendemos Francisco Beltrão, Dois Vizinhos, Coronel Vivida e outras cidades do Sudoeste do Paraná a partir de Foz do Iguaçu."),("Transfer Corporativo Foz–Pato Branco","Para empresas com operações em Foz do Iguaçu e Pato Branco, oferecemos transfer corporativo regular com condições especiais e o mesmo padrão premium em cada viagem."),("Reserve Transfer Foz–Pato Branco","Entre em contato pelo WhatsApp com data e horário. Orçamento em até 5 minutos.")]),
  ("transfer-foz-francisco-beltrao","Transfer Foz do Iguaçu para Francisco Beltrão PR","transfer foz francisco beltrao parana","Transfer executivo de Foz do Iguaçu para Francisco Beltrão PR. Motorista profissional e veículo premium.",[("Transfer Executivo Foz–Francisco Beltrão","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Francisco Beltrão no Sudoeste do Paraná. Viagem confortável em veículo premium com motorista profissional e experiente na rota."),("Francisco Beltrão e o Sudoeste do Paraná","Francisco Beltrão é um importante centro regional do Sudoeste do Paraná. Para executivos e empresários que precisam de transfer entre Foz do Iguaçu e Francisco Beltrão, oferecemos o serviço mais profissional da rota."),("Transfer Foz–Francisco Beltrão para Eventos","Para participar de eventos e reuniões em Francisco Beltrão vindo de Foz do Iguaçu, nosso transfer executivo garante chegada pontual e confortável para fazer a melhor impressão nos seus compromissos."),("Sudoeste do Paraná — Toda a Região Atendida","Além de Francisco Beltrão, atendemos Pato Branco, Dois Vizinhos, Ampére e outras cidades do Sudoeste do Paraná a partir de Foz do Iguaçu com o mesmo padrão premium."),("Reserve Transfer Foz–Francisco Beltrão","Entre em contato pelo WhatsApp com data, horário e endereços. Orçamento em até 5 minutos.")]),
  ("transfer-foz-medianeira","Transfer Foz do Iguaçu para Medianeira PR","transfer foz do iguacu medianeira parana","Transfer executivo de Foz do Iguaçu para Medianeira PR. Rápido, confortável e com motorista profissional.",[("Transfer Executivo Foz–Medianeira","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Medianeira, município vizinho a apenas 45 minutos. Ideal para executivos e turistas que precisam de transporte rápido e confortável entre as duas cidades."),("Medianeira — Cidade Vizinha de Foz do Iguaçu","Medianeira fica a apenas 45km de Foz do Iguaçu e é um importante polo agroindustrial do Oeste do Paraná. Nosso transfer executivo é a opção mais confortável para deslocamentos entre as duas cidades."),("Transfer Aeroporto Foz para Medianeira","Para passageiros que chegam ao Aeroporto IGU com destino a Medianeira, realizamos transfer direto com conforto e pontualidade. Também fazemos o trajeto inverso para embarques no aeroporto de Foz."),("Transfer Corporativo Foz–Medianeira","Para empresas com operações em Foz do Iguaçu e Medianeira, oferecemos transfer corporativo regular. Atendemos também Matelândia, Céu Azul e outras cidades próximas."),("Reserve Transfer Foz–Medianeira","Entre em contato pelo WhatsApp. Orçamento rápido em até 5 minutos.")]),
  ("transfer-foz-campo-mourao","Transfer Foz do Iguaçu para Campo Mourão PR","transfer foz do iguacu campo mourao parana","Transfer executivo de Foz do Iguaçu para Campo Mourão PR. Confortável com motorista profissional.",[("Transfer Executivo Foz–Campo Mourão","A Iguaçu Executive Transfer realiza transfer executivo entre Foz do Iguaçu e Campo Mourão no Centro-Oeste do Paraná. Viagem de aproximadamente 2h30min com total conforto em veículo premium."),("Campo Mourão — Centro-Oeste do Paraná","Campo Mourão é um importante polo regional do Centro-Oeste do Paraná com forte setor agrícola e industrial. Transfer executivo entre Foz do Iguaçu e Campo Mourão para executivos e empresários da região."),("Transfer Foz–Campo Mourão com Paradas","Nossa rota entre Foz do Iguaçu e Campo Mourão pode incluir paradas em Cascavel ou Guaraniaçu conforme necessidade. Personalizamos o roteiro para atender seus compromissos na região."),("Campo Mourão e Região Atendida","Além de Campo Mourão, atendemos Goioerê, Mamborê, Roncador e outras cidades da região Centro-Oeste do Paraná a partir de Foz do Iguaçu com o mesmo padrão de qualidade."),("Reserve Transfer Foz–Campo Mourão","Entre em contato pelo WhatsApp com data e horário. Orçamento em até 5 minutos.")]),
  ("transfer-foz-para-assuncao-paraguai","Transfer Foz do Iguaçu para Assunção Paraguai","transfer foz do iguacu assuncao paraguai","Transfer executivo de Foz do Iguaçu para Assunção no Paraguai. Motorista bilíngue e experiente.",[("Transfer Foz do Iguaçu para Assunção Paraguai","A Iguaçu Executive Transfer realiza transfer executivo de Foz do Iguaçu para Assunção, capital do Paraguai. Uma viagem de aproximadamente 5 horas com motorista bilíngue especializado em rotas internacionais e trâmites de fronteira."),("Assunção — Capital do Paraguai","Assunção é a capital e maior cidade do Paraguai, com importante polo de negócios e turismo. Para executivos e empresários que precisam ir a Assunção a partir de Foz do Iguaçu, nosso transfer é a opção mais confortável e segura."),("Travessia Brasil–Paraguai com Suporte Total","O transfer de Foz do Iguaçu para Assunção inclui suporte completo na travessia de fronteira em Ciudad del Este. Nosso motorista bilíngue cuida de toda a documentação e comunicação com autoridades."),("Aceitamos Real Dólar e Guarani","Para o transfer para Assunção, aceitamos pagamento em Real BRL, Dólar USD e Guarani PYG. Facilitamos ao máximo para viajantes de qualquer origem."),("Reserve Transfer Foz–Assunção Paraguai","Entre em contato pelo WhatsApp com data, horário e número de passageiros. Confirmamos orçamento em até 5 minutos.")]),
]

for slug, titulo, keyword, desc, secoes in paginas2:
    html = pagina(slug, titulo, keyword, desc, secoes)
    path = f"{BASE}/{slug}.html"
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)

total2 = len(paginas2)
print(f"✅ {total2} novas páginas geradas!")
print(f"✅ Total geral: {len(paginas)+total2} páginas CMS!")
